server:
  port: 8888
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.229.252:3306/zmmcktest?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: cktest
